import logging
import os
from typing import Dict, List, Optional, Union

from pydantic import Field, validator
from semver import VersionInfo

from .dimensions import DimensionReferenceModel
from dsgrid.data_models import DSGBaseModel
from dsgrid.dimension.base_models import DimensionType
from dsgrid.utils.versioning import handle_version_or_str


logger = logging.getLogger(__name__)


class DimensionMappingBaseModel(DSGBaseModel):
    """Base class for mapping dimensions"""

    from_dimension: DimensionReferenceModel = Field(
        title="from_dimension",
        description="from dimension",
    )
    to_dimension: DimensionReferenceModel = Field(
        title="to_dimension",
        description="to dimension",
    )
    description: str = Field(
        title="description",
        description="description of dimension mapping",
    )
    mapping_id: Optional[str] = Field(
        title="mapping_id",
        alias="id",
        description="unique identifier, generated by dsgrid",
    )


class DimensionMappingReferenceModel(DSGBaseModel):
    """Reference to a dimension mapping stored in the registry.

    The DimensionMappingReferenceModel is utilized by the project configuration (project.toml) as well as by the dimension mapping reference configuration (dimension_mapping_references.toml) that may be required when submitting a dataset to a project.
    """

    from_dimension_type: DimensionType = Field(
        title="from_dimension_type",
        description="type of the dimension",
    )
    to_dimension_type: DimensionType = Field(
        title="to_dimension_type",
        description="type of the dimension",
    )
    mapping_id: str = Field(
        title="mapping_id",
        description="unique ID of the dimension mapping",
    )
    version: Union[str, VersionInfo] = Field(
        title="version",
        description="version of the dimension",
    )
    required_for_validation: Optional[bool] = Field(
        title="version",
        description="set to False if a given base-to-base dimension mapping is NOT required for input dataset validation; default is True",
        default=True,
    )

    @validator("version")
    def check_version(cls, version):
        return handle_version_or_str(version)

    # @validator("required_for_validation")
    # def check_required_for_validation_field(cls, value):
    #     # TODO if base_to_supplemental, raise error
    #     return value
