import logging
import os
from typing import Dict, List, Optional, Union

from pydantic import Field, validator
from semver import VersionInfo

from .dimensions import DimensionReferenceModel
from dsgrid.data_models import DSGBaseModel, DSGEnum
from dsgrid.dimension.base_models import DimensionType
from dsgrid.utils.versioning import handle_version_or_str


logger = logging.getLogger(__name__)


class DimensionMappingArchetype(DSGEnum):
    ONE_TO_ONE = "one_to_one"
    ONE_TO_MANY = "one_to_many"
    MANY_TO_ONE = "many_to_one"
    MANY_TO_MANY = "many_to_many"


class FractionSumType(DSGEnum):
    EQUAL_TO_ONE = "equal_to_one"
    LESS_THAN_ONE = "less_than_one"
    GREATER_THAN_ONE = "greater_than_one"


class DimensionMappingBaseModel(DSGBaseModel):
    """Base class for mapping dimensions"""

    archetype: DimensionMappingArchetype = Field(
        title="archetype",
        description="Dimension mapping archetype, used to check whether duplicates are allowed in from and to dimension",
        default="many_to_one",
        options=DimensionMappingArchetype.format_for_docs(),
    )
    from_fraction_sum: FractionSumType = Field(
        title="from_fraction_sum",
        description="Specify whether sum of from_fraction should be =, <, or > 1 when group by from_id",
        default="equal_to_one",
        options=FractionSumType.format_for_docs(),
    )
    from_dimension: DimensionReferenceModel = Field(
        title="from_dimension",
        description="From dimension",
    )
    to_dimension: DimensionReferenceModel = Field(
        title="to_dimension",
        description="To dimension",
    )
    description: str = Field(
        title="description",
        description="Description of dimension mapping",
    )
    mapping_id: Optional[str] = Field(
        title="mapping_id",
        alias="id",
        description="Unique dimension mapping identifier, generated by dsgrid",
        dsg_internal=True,
        updateable=False,
    )


class DimensionMappingReferenceModel(DSGBaseModel):
    """Reference to a dimension mapping stored in the registry.

    The DimensionMappingReferenceModel is utilized by the project configuration (project.toml) as well as by the dimension mapping reference configuration (dimension_mapping_references.toml) that may be required when submitting a dataset to a project.
    """

    from_dimension_type: DimensionType = Field(
        title="from_dimension_type",
        description="Dimension Type",
        options=DimensionType.format_for_docs(),
    )
    to_dimension_type: DimensionType = Field(
        title="to_dimension_type",
        description="Dimension Type",
        options=DimensionType.format_for_docs(),
    )
    mapping_id: str = Field(
        title="mapping_id",
        description="Unique ID of the dimension mapping",
        updateable=False,
    )
    version: Union[str, VersionInfo] = Field(
        title="version",
        description="Version of the dimension",
        # TODO: add notes about warnings for outdated versions DSGRID-189 & DSGRID-148
    )
    required_for_validation: Optional[bool] = Field(
        title="version",
        description="Set to False if a given base-to-base dimension mapping is NOT required for input dataset validation; default is True",  # outdated, FIXME
        default=True,
        # TODO: add notes about warnings for outdated versions DSGRID-189 & DSGRID-148
    )

    @validator("version")
    def check_version(cls, version):
        return handle_version_or_str(version)

    # @validator("required_for_validation")
    # def check_required_for_validation_field(cls, value):
    #     # TODO if base_to_supplemental, raise error
    #     return value


class DimensionMappingReferenceListModel(DSGBaseModel):
    """List of dimension mapping references used by the dimensions_mappings.toml config"""

    references: List[DimensionMappingReferenceModel] = Field(
        title="references",
        description="List of dimension mapping references",
    )
